observerly/polaris

src/astrometry/getEquatorialCoordinateProperMotionCorrected.ts, src/astrometry/index.ts, src/index.ts, tests/astrometry.test.ts
feat: Added getEquatorialCoordinateProperMotionCorrected() to astrometry module.
=> feat: Added getEquatorialCoordinateProperMotionCorrected().

src/astrometry/getParallacticAngle.ts, src/astrometry/index.ts, src/index.ts, tests/astrometry.test.ts
feat: Added getParallacticAngle() to astrometry module. 
=> feat: Added getParallacticAngle().

src/utilities/convertDegreeToDMS.ts, src/utilities/parseDegreeToDMSHumanised.ts, tests/utilities.test.ts
fix: Amended convertDegreeToDMS() and convertDegreeToDMS() in utilities module.
Includes associated test suite changes for module export definition and expected output.
=> fix: Amended convertDegreeToDMS() and parseDegreeToHumanised().

src/utilities/convertDegreeToHMS.ts, src/utilities/parseDegreeToHMSHumanised.ts, tests/utilities.test.ts
fix: Amended convertDegreeToHMS() and convertDegreeToHMS() in utilities module. 
Includes associated test suite changes for module export definition and expected output.
=> fix: Amended convertDegreeToHMS() and convertDegreeToHMS().

src/index.ts, src/lunar/getLunarPhaseName.ts, src/lunar/index.ts, tests/lunar.test.ts
feat: Added getLunarPhaseName() to lunar module. 
=> feat: Added getLunarPhaseName().

.github/workflows/publish.yml, .github/workflows/test.yml
chore: Upgrade ci workflow runners to use pnpm package manager.
=> chore: Upgrade ci workflow runners to use pnpm package manager.

src/astrometry/getOrthodromicAngluarDistance.ts, src/astrometry/index.ts, src/index.ts, tests/astrometry.test.ts
feat: Added getOrthodromicAngluarDistance() to astrometry module. 
=> feat: Added getOrthodromicAngluarDistance() to astrometry module.

src/epoch/index.ts, src/index.ts
feat: Added { J1900, J2000, ... } to exported members.
=> feat: Added { J1900, J2000, ... } to exported members.

src/index.ts, src/observer/index.ts, src/observer/observer.ts, src/observer/useObserver.ts, tests/observer.test.ts
feat: Added useObserver() composable to observer module. 
Includes adding Observer class as the new Proxy() target. 
=> feat: Added useObserver() composable to observer module.

src/index.ts, src/observation/getAirmass.ts, src/observation/index.ts, tests/observation.test.ts
feat: Added getAirmass() to observation module. 
=> feat: Added getAirmass() to observation module.

src/epoch/getUniversalTime.ts, tests/epoch.test.ts
feat: Added getUniversalTime() to epoch module. 
=> feat: Added getUniversalTime() to epoch module.

src/index.ts, src/solar/getSolarMeanTime.ts, src/solar/index.ts, tests/solar.test.ts
feat: Added getSolarMeanTime() to solar module. 
=> feat: Added getSolarMeanTime() to solar module.

src/index.ts, src/solar/getSolarEclipticLongitude.ts, src/solar/index.ts, tests/solar.test.ts
feat: Added getSolarEclipticLongitude() to solar module. 
=> feat: Added getSolarEclipticLongitude() to solar module.

src/index.ts, src/solar/getSolarHourAngle.ts, src/solar/index.ts, tests/index.ts, tests/solar.test.ts
feat: Added getSolarHourAngle() to solar module. 
=> feat: Added getSolarHourAngle() to solar module.

src/index.ts, src/solar/getSolarTransitJulianDate.ts, src/solar/index.ts, tests/solar.test.ts
feat: Added getSolarTransitJulianDate() to solar module. 
=> feat: Added getSolarTransitJulianDate() to solar module.

src/epoch/constants.ts, src/epoch/index.ts, src/index.ts
feat: Added the Julian Date for J1970 to epoch module. 
=> feat: Added the Julian Date for J1970 to epoch module.

src/index.ts, src/solar/getSolarRiseSet.ts, src/solar/index.ts, tests/solar.test.ts
feat: Added getSolarRiseSet() to solar module. 
=> feat: Added getSolarRiseSet() to solar module.

src/index.ts, src/transit/index.ts, src/transit/isAboveHorizon.ts, tests/transit.test.ts
feat: Added isAboveHorizon() to transit module. 
=> feat: Added isAboveHorizon() to transit module.

.github/workflows/test.yml
ci: Lock pnpm global dependency version to 7.30.0.
=> ci: Lock pnpm global dependency version to 7.30.0.

src/index.ts, src/planets/getPlanetaryEquationOfCenter.ts, src/planets/index.ts, tests/planets.test.ts
feat: Added getPlanetaryEquationOfCenter() to planets module. 
=> feat: Added getPlanetaryEquationOfCenter() to planets module.

src/index.ts, src/planets/getPlanetaryEquationOfCenter.ts, src/planets/getPlanetaryTrueAnomaly.ts, src/planets/index.ts, tests/planets.test.ts
feat: Added getPlanetaryTrueAnomaly() to planets module. 
=> feat: Added getPlanetaryTrueAnomaly() to planets module.

src/types/coordinates.ts, src/types/index.ts
feat: Added HeliocentricEclipticCoordinate type.
=> feat: Added HeliocentricEclipticCoordinate type.

src/types/bodies.ts, src/types/index.ts
=> feat: Added Planet type.

src/index.ts, src/planets/getPlanetaryHeliocentricEclipticCoordinate.ts, src/planets/index.ts, tests/planets.test.ts
feat: Added getPlanetaryHeliocentricEclipticCoordinate() to planets module. 
=> feat: Added getPlanetaryHeliocentricEclipticCoordinate() to planets module.

package.json, pnpm-lock.yaml
chore: Updated typescript => v4.9.5 devDependency.
=> chore: Updated typescript => v4.9.5 devDependency.

src/index.ts, src/planets/index.ts, src/planets/mercury.ts
feat: Added Mercury constant to planets module.
=> feat: Added Mercury constant to planets module.

package.json, pnpm-lock.yaml
chore: Updated vite => v4.2.1 devDependency. 
Includes updating associated vite related dependencies for bunding and testing.
=> chore: Updated vite => v4.2.1 devDependency.

src/index.ts, src/planets/earth.ts, src/planets/index.ts
feat: Added Earth constant to planets module.
=> feat: Added Earth constant to planets module.

src/index.ts, src/planets/index.ts, src/planets/mars.ts
feat: Added Mars constant to planets module.
=> feat: Added Mars constant to planets module.

src/index.ts, src/planets/index.ts, src/planets/jupiter.ts
feat: Added Jupiter constant to planets module.
=> feat: Added Jupiter constant to planets module.

src/index.ts, src/planets/index.ts, src/planets/saturn.ts
feat: Added Saturn constant to planets module.
=> feat: Added Saturn constant to planets module.

src/index.ts, src/planets/index.ts, src/planets/uranus.ts
feat: Added Uranus constant to planets module.
=> feat: Added Uranus constant to planets module.

src/index.ts, src/planets/index.ts, src/planets/neptune.ts
feat: Added Neptune constant to planets module.
=> feat: Added Neptune constant to planets module.

src/coordinates/convertEclipticToEquatorial.ts
feat: Amend { ra } calculation to use Math.atan2 in convertEclipticToEquatorial() in coordinates module.
=> feat: Amend { ra } calculation to use Math.atan2 in convertEclipticToEquatorial() in coordinates module.

src/index.ts, src/planets/getPlanetaryEclipticCoordinate.ts, src/planets/index.ts, tests/planets.test.ts
feat: Added getPlanetaryEclipticCoordinate() to planets module. 
=> feat: Added getPlanetaryEclipticCoordinate() to planets module.

src/astrometry/getHourAngle.ts
refactor: Amend getHourAngle() to return normalised degree.
=> refactor: Amend getHourAngle() to return normalised degree in astrometry module.

src/astrometry/getParallacticAngle.ts, tests/astrometry.test.ts
fix: Amended getParallacticAngle() to return correct values in astrometry module. 
=> fix: Amended getParallacticAngle() to return correct values in astrometry module.

src/index.ts
chore: Amend root src/index.ts to export * for simplicity.
=> chore: Amend root src/index.ts to export * for simplicity.

src/utilities/parseDegreeToDMSHumanised.ts, tests/utilities.test.ts
fix: Amend parseDegreeToDMSHumanised() in utilities module. 
Includes associated test suite amends for module export definition and expected output.
=> fix: Amend parseDegreeToDMSHumanised() in utilities module.
